import type { EducationLevel } from "../types";

export const educationLevels: EducationLevel[] = [
  {
    id: 1,
    title: "Evliliğin Önemi ve Niyet",
    description: "İslam'da evliliğin yeri, hikmeti ve fazileti",
    contents: [
      { id: "1-l1", type: "letter", title: "Evliliğini Geciktirmek İsteyen Gence Mektup", url: "https://fetvameclisi.com/fetva/evliligini-geciktirmek-isteyen-gence-mektup" },
      { id: "1-l2", type: "letter", title: "Evlilik Bir İbadet Midir?", url: "https://fetvameclisi.com/fetva/evlilige-niyet-etmek" },
      { id: "1-l3", type: "letter", title: "Haram Sevda Kıskacındaki Gence Tavsiyeler", url: "https://fetvameclisi.com/fetva/haram-sevda-kiskacindaki-gence-mektup" },
      { id: "1-v1", type: "video", title: "Evlilik Bir Tercih Değil, Bir Zarurettir", url: "https://www.youtube.com/watch?v=iJtr25H4ufA" },
      { id: "1-v2", type: "video", title: "Neden Evlenmeliyiz? Hikmetler ve Gayeler", url: "https://www.youtube.com/watch?v=3A7Qyv-6AtQ" },
      { id: "1-v3", type: "video", title: "Gençlik ve İffet Mücadelesinde Evliliğin Rolü", url: "https://www.youtube.com/watch?v=Mh99yLNi3zk" },
    ],
    quiz: [
      { id: "1-q1", question: "İslam hukukuna göre evliliğin 'ibadet' sayılabilmesi için en temel şart hangisidir?", options: ["Düğün merasiminin gösterişli olması", "İffeti koruma ve salih nesil yetiştirme niyeti", "Maddi imkanların en üst seviyede olması", "Ev eşyalarının eksiksiz olması"], correctIndex: 1, hint: "Ameller niyetlere göredir. Herkese ancak niyet ettiği şey vardır.", source: "Buhârî, Bed'ü'l-vahy, 1" },
      { id: "1-q2", question: "Maddi imkansızlık bahanesiyle evliliği erteleyen bir genç neyi ihmal etmiş olur?", options: ["Kariyer fırsatlarını", "Allah'ın vaadine olan tevekkülü", "Kişisel özgürlüğünü", "Sosyal çevresini"], correctIndex: 1, hint: "Eğer fakirseler, Allah onları lütfuyla zengin eder.", source: "Nûr Suresi, 32" },
      { id: "1-q3", question: "Evlilik niyetinde 'nesil endişesi' taşımak neyi hedefler?", options: ["Çocuk sayısının çokluğunu", "Miras bırakacak birini bulmayı", "İslam ahlakıyla donanmış kaliteli bir nesil yetiştirmeyi", "Çocukların sadece dünyevi kariyerlerini"], correctIndex: 2, hint: "Ölünce insanın ameli kesilir; ancak kendisine dua eden salih evlat müstesna.", source: "Müslim, Vasiyye, 14" },
      { id: "1-q4", question: "Evlenmek hangi durumda 'farz' derecesine çıkar?", options: ["Yaş 30'u geçtiğinde", "Harama düşme ihtimali kesinleştiğinde", "Aile baskısı arttığında", "Maddi birikim tamamlandığında"], correctIndex: 1, hint: "Kimin evlenmeye gücü yetiyorsa evlensin. Çünkü evlilik gözü haramdan sakındırır.", source: "Buhârî, Nikâh, 3" },
      { id: "1-q5", question: "İslam'da bekarlık hali nasıl değerlendirilir?", options: ["Saltanattır", "Dinin yarısından mahrum bir korunmasızlık halidir", "Tercihe bağlı üstünlüktür", "Sadece yaşlılıkta zordur"], correctIndex: 1, hint: "Kul evlendiği vakit, dininin yarısını tamamlamış olur.", source: "Beyhakî, Şuabü'l-Îmân, 5486" },
    ],
  },
  {
    id: 2,
    title: "Mehir, Nikâh ve Düğün Adabı",
    description: "Nikâhın şartları, mehir ve düğün adabı",
    contents: [
      { id: "2-l1", type: "letter", title: "Mehir Hakkında Bilinmesi Gerekenler", url: "https://fetvameclisi.com/fetva/578-mehir-nedir-ve-ne-zaman-odenmelidir" },
      { id: "2-l2", type: "letter", title: "İslami Bir Düğün Nasıl Olmalı?", url: "https://fetvameclisi.com/fetva/dugun-adabi-hakkinda" },
      { id: "2-l3", type: "letter", title: "Resmi Nikâh ve Sorumluluklar", url: "https://fetvameclisi.com/fetva/nikah-ve-resmiyet" },
      { id: "2-v1", type: "video", title: "Nikâhın Rükünleri ve Şartları", url: "https://www.youtube.com/watch?v=3A7Qyv-6AtQ" },
      { id: "2-v2", type: "video", title: "Mehir: Kadının Güvencesi", url: "https://www.youtube.com/watch?v=cKf4YluMOAg" },
      { id: "2-v3", type: "video", title: "Düğünlerdeki İsraf ve Yanlış Adetler", url: "https://www.youtube.com/watch?v=Mh99yLNi3zk" },
    ],
    quiz: [
      { id: "2-q1", question: "Mehir miktarı belirlenirken temel ölçü ne olmalıdır?", options: ["Çok yüksek olmalı", "Erkeği zorlamayacak makul bir miktar", "Sembolik olmalı", "Akrabaların kararı olmalı"], correctIndex: 1, hint: "Nikâhın en hayırlısı, külfeti en az olanıdır.", source: "Ebû Dâvûd, Nikâh, 32" },
      { id: "2-q2", question: "Nikâhın ilan edilmesinin (gizli kalmamasının) amacı nedir?", options: ["Takı toplamak", "Nesebin ve kadının haklarının korunması", "Resmi evrak işleri", "Şov yapmak"], correctIndex: 1, hint: "Nikâhı ilan edin, onu mescitlerde yapın.", source: "Tirmizî, Nikâh, 6" },
      { id: "2-q3", question: "Düğünlerdeki israfın sınırı nedir?", options: ["Yemek ikramı", "Gösteriş amaçlı ve geleceği borçlandıran harcamalar", "Davetli sayısı", "Müzik kullanımı"], correctIndex: 1, hint: "Yiyin, için, giyinin; ancak israfa ve kibre kaçmayın.", source: "Buhârî, Libâs, 1" },
      { id: "2-q4", question: "Ertelenmiş mehir (Müeccel) ne zaman erkeğin üzerine borç olur?", options: ["Hiçbir zaman", "Erkek istediğinde", "Boşanma, ölüm veya kadının talebinde", "Çocuk olduğunda"], correctIndex: 2, hint: "Kadınlara mehirlerini gönül rızasıyla verin.", source: "Nisâ Suresi, 4" },
      { id: "2-q5", question: "Düğünlerde mahremiyet sınırı neyi ifade eder?", options: ["Kimsenin çağrılmamasını", "Kadın ve erkeğin harama girmeden eğlendiği ortamı", "Fotoğraf yasağını", "Sadece akraba katılımını"], correctIndex: 1, hint: "Mü'min erkeklere ve kadınlara söyle, gözlerini haramdan sakınsınlar.", source: "Nûr Suresi, 30-31" },
    ],
  },
  {
    id: 3,
    title: "Görüşme Usulü",
    description: "İslami adaba uygun görüşme ve tanışma kuralları — GATE SEVİYESİ",
    contents: [
      { id: "3-l1", type: "letter", title: "Evlilik Görüşmesi Yapan Gence Mektup", url: "https://fetvameclisi.com/fetva/evlilik-gorusmesi-nasil-olmali-diye-soran-musluman-gence-mektup" },
      { id: "3-l2", type: "letter", title: "Eş Seçerken Hangi Kriterlere Bakılmalı?", url: "https://fetvameclisi.com/fetva/es-secimi-kriterleri" },
      { id: "3-l3", type: "letter", title: "İstihare ve İstişare Nasıl Yapılır?", url: "https://fetvameclisi.com/fetva/evlilikte-istihare" },
      { id: "3-v1", type: "video", title: "Görüşme Odasında Neler Konuşulur?", url: "https://www.youtube.com/watch?v=3A7Qyv-6AtQ" },
      { id: "3-v2", type: "video", title: "Adaylarda Aranacak 3 Temel Özellik", url: "https://www.youtube.com/watch?v=iJtr25H4ufA" },
      { id: "3-v3", type: "video", title: "Nişanlılık Dönemi Hataları", url: "https://www.youtube.com/watch?v=Mh99yLNi3zk" },
    ],
    quiz: [
      { id: "3-q1", question: "Görüşmelerde 'halvet' yasağının sınırı nedir?", options: ["Bakışmak", "Başkası görmeyecek şekilde baş başa kalmak", "Telefonlaşmak", "Mesajlaşmak"], correctIndex: 1, hint: "Bir erkek, yanında mahremi olmayan kadınla baş başa kalmasın.", source: "Müslim, Hac, 424" },
      { id: "3-q2", question: "Görüşmeden sadece mesajla evlilik kararı neden risklidir?", options: ["Yavaş ilerler", "Mizaç uyumunu ve simayı görmeyi engellediği için", "Kontör biter", "Aileler kızar"], correctIndex: 1, hint: "Evlenmek istediğiniz kadının sizi evliliğe sevk edecek bölgelerine (yüzüne) bakın.", source: "Ebû Dâvûd, Nikâh, 18" },
      { id: "3-q3", question: "İstiharede asıl belirleyici olan nedir?", options: ["Renk görmek", "Kalpteki ferahlık ve işlerin kolaylaşması", "Rakamlar", "Başkasının rüyası"], correctIndex: 1, hint: "Allahım! Bu iş dinim ve dünyam için hayırlı ise onu bana kolaylaştır.", source: "Buhârî, Teheccüd, 25" },
      { id: "3-q4", question: "Görüşmede 'yalan söylemek' hangi kapsama girer?", options: ["Basit hata", "Aldatma (Gışş) ve güven yıkımı", "Beyaz yalan", "Strateji"], correctIndex: 1, hint: "Bizi aldatan, bizden değildir.", source: "Müslim, Îmân, 164" },
      { id: "3-q5", question: "Veli haberdar olmadan yapılan görüşmelerin riski nedir?", options: ["Pazarlık yapılamaz", "Kızın suistimal edilmesi ve tecrübe eksikliği", "Süre uzar", "Düğün olmaz"], correctIndex: 1, hint: "Veli ve iki adil şahit olmadan nikâh geçerli değildir.", source: "Ebû Dâvûd, Nikâh, 19" },
    ],
  },
  {
    id: 4,
    title: "Aile Kurma ve Roller",
    description: "Aile reisi olmanın sorumlulukları ve karşılıklı haklar",
    contents: [
      { id: "4-l1", type: "letter", title: "Aile Reisi Olmak İsteyen Erkeğe Mektup", url: "https://fetvameclisi.com/fetva/aile-reisi-olmak" },
      { id: "4-l2", type: "letter", title: "Eşlerin Karşılıklı Hak ve Görevleri", url: "https://fetvameclisi.com/fetva/eslerin-birbirine-karsi-sorumluluklari" },
      { id: "4-l3", type: "letter", title: "Gelin-Kaynana ve Aile İçi Denge", url: "https://fetvameclisi.com/fetva/aile-ici-denge-ve-mudahaleler" },
      { id: "4-v1", type: "video", title: "Kavvam Olmak: Erkeğin Liderliği", url: "https://www.youtube.com/watch?v=cKf4YluMOAg" },
      { id: "4-v2", type: "video", title: "Saliha Kadının Evdeki Rolü", url: "https://www.youtube.com/watch?v=Mh99yLNi3zk" },
      { id: "4-v3", type: "video", title: "Ailelerin Müdahalesi Nereye Kadar?", url: "https://www.youtube.com/watch?v=iJtr25H4ufA" },
    ],
    quiz: [
      { id: "4-q1", question: "Erkeğin 'Kavvam' olması ne anlama gelir?", options: ["Sertlik yetkisi", "Yönetme, koruma ve geçim sorumluluğu", "Her kararı tek alma hakkı", "Evden uzak durma"], correctIndex: 1, hint: "Erkekler, kadınlar üzerinde kavvâmdır (koruyucudur).", source: "Nisâ Suresi, 34" },
      { id: "4-q2", question: "Kadının kocasına itaati hangi durumda geçerli değildir?", options: ["Maddi isteklerde", "Allah'ın emrine aykırı bir istek olduğunda", "Keyfi durumlarda", "Ailesi istemediğinde"], correctIndex: 1, hint: "Allah'a isyan olan konuda kula itaat edilmez.", source: "Müslim, İmâre, 39" },
      { id: "4-q3", question: "Eşlerin birbirine sadakati neleri kapsar?", options: ["Sadece fiziksel sadakat", "Duygusal bağ, sır saklama ve onur koruma", "Şifre paylaşımı", "Aynı evde durma"], correctIndex: 1, hint: "Onurlar sizin için bir elbise, siz de onlar için bir elbisesiniz.", source: "Bakara Suresi, 187" },
      { id: "4-q4", question: "Eşlerin ailelerine karşı duruşu nasıl olmalıdır?", options: ["Bağları koparmalı", "Hürmet etmeli ama çekirdek ailenin mahremiyetini korumalı", "Her şeyi sormalı", "Mesafe koymalı"], correctIndex: 1, hint: "Büyüklerimize saygı göstermeyen bizden değildir.", source: "Tirmizî, Birr, 15" },
      { id: "4-q5", question: "Ev işleri sadece kadının görevi midir?", options: ["Evet", "Hayır, sorumluluklar paylaşılmalıdır", "Kadın çalışmıyorsa evet", "Erkek isterse evet"], correctIndex: 1, hint: "Peygamber Efendimiz evde ailesinin işlerine yardım ederdi.", source: "Buhârî, Ezan, 44" },
    ],
  },
  {
    id: 5,
    title: "Mutlu Evliliğin Sırları",
    description: "Evlilikte iletişim, sabır ve şükür",
    contents: [
      { id: "5-l1", type: "letter", title: "Evliliğinde Mutsuz Olanlara Sabır Mektubu", url: "https://fetvameclisi.com/fetva/mutsuz-evlilik-icin-nasihat" },
      { id: "5-l2", type: "letter", title: "Yatak Odası Mahremiyeti ve Sınırları", url: "https://fetvameclisi.com/fetva/yatak-odasi-mahremiyeti" },
      { id: "5-l3", type: "letter", title: "Tartışma ve Geçim Adabı", url: "https://fetvameclisi.com/fetva/tartisma-ve-gecim-adabi" },
      { id: "5-v1", type: "video", title: "Evlilikte İlk Bir Yılın Önemi", url: "https://www.youtube.com/watch?v=cKf4YluMOAg" },
      { id: "5-v2", type: "video", title: "Mutlu Evlilik İçin 11 Altın Kural", url: "https://www.youtube.com/watch?v=Mh99yLNi3zk" },
      { id: "5-v3", type: "video", title: "Boşanmaya Götüren Sebepler", url: "https://www.youtube.com/watch?v=iJtr25H4ufA" },
    ],
    quiz: [
      { id: "5-q1", question: "Tartışma anında Müslüman edebi nasıldır?", options: ["Ses yükseltmek", "Ses yükseltmemek ve hakaret etmemek", "Küsmek", "Eski hataları açmak"], correctIndex: 1, hint: "Mü'min; kötü söz söyleyen ve lanetleyen biri değildir.", source: "Tirmizî, Birr, 48" },
      { id: "5-q2", question: "Özel mahremiyetin dışarıya anlatılmasının sonucu nedir?", options: ["Arkadaşlık pekişir", "Emanete hıyanet ve büyük günahtır", "Nazar değer", "Deşarj olunur"], correctIndex: 1, hint: "Kıyamet günü konumu en kötü olan, eşinin sırrını yayandır.", source: "Müslim, Nikâh, 123" },
      { id: "5-q3", question: "Evlilikte sabır ne demektir?", options: ["Boyun eğmek", "Zorlukları birlikte aşmak ve fevri olmamak", "Sadece erkeğin susması", "Boşanmayı beklemek"], correctIndex: 1, hint: "Hoşlanmadığınız bir huyun yanında memnun kalacağınız bir huy mutlaka vardır.", source: "Müslim, Radâ, 61" },
      { id: "5-q4", question: "Eşlerin birbirine teşekkür etmesi neyi ifade eder?", options: ["Nezaket", "Nimetin şükrü ve vefa borcu", "Şımartma", "Formalite"], correctIndex: 1, hint: "İnsanlara teşekkür etmeyen, Allah'a da şükretmiş olmaz.", source: "Tirmizî, Birr, 35" },
      { id: "5-q5", question: "Çözülemeyen krizlerde Kur'an'ın tavsiyesi nedir?", options: ["Hemen boşanmak", "Ailelerden hakem tayin etmek", "Mahkemeye gitmek", "Herkesi karıştırmak"], correctIndex: 1, hint: "Aranın açılmasından korkarsanız, her iki aileden birer hakem gönderin.", source: "Nisâ Suresi, 35" },
    ],
  },
];
